/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.wanasit.kotori.mecab

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull


class TestMeCabCharDefinitionLookup {

    @Test fun testReadingCharDef() {
        val definitionLookup = MeCabCharDefinitionLookup.read("""
            DEFAULT         0 1 0  # DEFAULT is a mandatory category!
            KATAKANA        1 1 2  
            SYMBOL	        1 1 0
            OTHER           0 1 0
            

            0xFF10..0xFF19 OTHER SYMBOL
            0x30FC         KATAKANA
        """.lines()
        )

        assertNotNull(definitionLookup)

        assertEquals(4, definitionLookup.categoryDefinitions().size)

        assertEquals("DEFAULT", definitionLookup.lookupCategoryDefinition(0).categoryName)
        assertEquals("KATAKANA", definitionLookup.lookupCategoryDefinition(1).categoryName)
        assertEquals("SYMBOL", definitionLookup.lookupCategoryDefinition(2).categoryName)

        assertEquals(true, definitionLookup.lookupCategoryDefinition(1).invoke)
        assertEquals(true, definitionLookup.lookupCategoryDefinition(1).group)


        assertEquals(intArrayOf(0).toSet(), definitionLookup.lookupCharCategories(0x0000.toChar()).toSet())
        assertEquals(intArrayOf(1).toSet(), definitionLookup.lookupCharCategories(0x30FC.toChar()).toSet())
        assertEquals(intArrayOf(2, 3).toSet(), definitionLookup.lookupCharCategories(0xFF19.toChar()).toSet())
    }

    @Test fun testReadingCharDefWithOverlapAssign() {

        val definitionLookup = MeCabCharDefinitionLookup.read("""
            DEFAULT         0 1 0  
            SYMBOL	        1 1 0
            0xFF10..0xFF19 SYMBOL
            
            # Re-define the value
            OTHER           0 1 0
            0xFF10..0xFF19 OTHER SYMBOL
        """.lines()
        )

        assertNotNull(definitionLookup)

        assertEquals(3, definitionLookup.categoryDefinitions().size)

        assertEquals(intArrayOf(1, 2).toSet(), definitionLookup.lookupCharCategories(0xFF19.toChar()).toSet())
    }
}



